#FROM ubuntu:16.04
FROM nvidia/cuda:10.0-runtime-ubuntu16.04

# To make it easier for build and release pipelines to run apt-get,
# configure apt to not require confirmation (assume the -y argument by default)
ENV DEBIAN_FRONTEND=noninteractive
RUN echo "APT::Get::Assume-Yes \"true\";" > /etc/apt/apt.conf.d/90assumeyes

RUN apt-get update \
&& apt-get install -y --no-install-recommends \
        ca-certificates \
        curl \
        jq \
        git \
        iputils-ping \
        libcurl3 \
        libicu55

WORKDIR /azp

# if the pool stops accepting jobs, check that there is not a new agent to download
# https://dev.azure.com/c3srdev/_settings/agentpools
RUN curl -LsS https://vstsagentpackage.azureedge.net/agent/2.152.1/vsts-agent-linux-x64-2.152.1.tar.gz | tar -xz
COPY ./start.sh .

RUN chmod +x start.sh

CMD ["./start.sh"]
